import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import HeaderDefaultHome from "./main_components/HeaderDefaultHome";
import { Providers } from "./providers";

const roboto = Roboto({
  weight: '700',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Badge_me",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={roboto.className}>
        <Providers>
          <HeaderDefaultHome />
          <main className="flex flex-col flex-1">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
